// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRspAI1sMYfPObXaePJ-Ei8dfvttiHrwQ',
    appId: '1:49703329928:web:c29357ec41738ad790ff3d',
    messagingSenderId: '49703329928',
    projectId: 'pemrograman-mobile-41673',
    authDomain: 'pemrograman-mobile-41673.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-41673.appspot.com',
    measurementId: 'G-EH2Y0J6XK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTesLxd_Y2nhZWf65pNIIiOezOMdne4M',
    appId: '1:49703329928:android:8ff46de20ae53cfd90ff3d',
    messagingSenderId: '49703329928',
    projectId: 'pemrograman-mobile-41673',
    storageBucket: 'pemrograman-mobile-41673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5oN_0pA1HuXljZxFRyVqHnbB4QIjLk5Q',
    appId: '1:49703329928:ios:873d8ae0682b33db90ff3d',
    messagingSenderId: '49703329928',
    projectId: 'pemrograman-mobile-41673',
    storageBucket: 'pemrograman-mobile-41673.appspot.com',
    iosBundleId: 'my.id.wulan.pert6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5oN_0pA1HuXljZxFRyVqHnbB4QIjLk5Q',
    appId: '1:49703329928:ios:873d8ae0682b33db90ff3d',
    messagingSenderId: '49703329928',
    projectId: 'pemrograman-mobile-41673',
    storageBucket: 'pemrograman-mobile-41673.appspot.com',
    iosBundleId: 'my.id.wulan.pert6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRspAI1sMYfPObXaePJ-Ei8dfvttiHrwQ',
    appId: '1:49703329928:web:46aabf7537a6b5d990ff3d',
    messagingSenderId: '49703329928',
    projectId: 'pemrograman-mobile-41673',
    authDomain: 'pemrograman-mobile-41673.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-41673.appspot.com',
    measurementId: 'G-XQZ53LCNKT',
  );
}
